name: Desplegar Frontend a GitHub Pages

on:
  push:
    branches: ["main"] # Se activa cada vez que subes algo a main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Subir carpeta frontend
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'frontend' # <--- ¡Aquí está el truco! GitHub solo leerá lo que esté dentro de esta carpeta

      - name: Publicar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4